services:
  # Load Balancer (Entry Point)
  interviews.local.zthunworks.com:
    image: zthun/bouncer
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./.config:/.config
    depends_on:
      - interview-react

  # Node Ports
  interview-nest:
    image: node:lts
    ports:
      - 9229:9229
    volumes:
      - .:/usr/dev
    working_dir: /usr/dev
    command: yarn workspace @zthun/interview-nest debug
  interview-react:
    image: node:lts
    volumes:
      - .:/usr/dev
    working_dir: /usr/dev
    command: yarn workspace @zthun/interview-react start
